<?php

/**
 * @author Freiler Béla
 * @copyright 2017
 */



?>
            <?php include "includes/widgets/asside.php"; ?>
            <article id="main">
            
                <?php
                foreach ($user_data as $key => $value) {
                    echo $key.": ".$value.'<br />';
                }
                ?>
                <!-- <p>
                    Nulla justo diam accusam consetetur ut sanctus nonumy invidunt elit dolore. Accusam tempor amet duo ea diam dolore duis diam sed erat. Dolore diam. Aliquip dolore sit dolore eirmod clita tincidunt dolore gubergren blandit sadipscing. Vero sed iusto sed sit est erat no illum invidunt. Sanctus et tempor sit. Stet ea eros. Consequat gubergren magna ut invidunt adipiscing vero tempor imperdiet dolor. Erat ipsum assum justo. Luptatum et invidunt sit amet sed ipsum illum et lorem volutpat. Dolor gubergren exerci ut eum dolor ipsum diam nonumy. Zzril molestie diam dolor ea laoreet no et erat. Liber vero. Lorem eos veniam eirmod no ipsum. Te dolor lorem et autem stet invidunt justo. Sed est sit elitr. Eos nonummy invidunt est diam nonummy adipiscing dolore et. Aliquyam voluptua sea. Sadipscing sed eum. Veniam sanctus autem duo diam aliquyam. Sed voluptua consequat zzril ullamcorper sit invidunt erat. Vero clita qui amet wisi. Iriure magna. Dolor takimata. Aliquam iusto. Ipsum sadipscing facilisis nonumy volutpat tempor minim dolore accusam ea. Et diam erat sit takimata vel odio sanctus eirmod ut. Praesent eirmod euismod cum vulputate clita minim dolor vel. Feugiat sanctus lorem tempor odio amet et vel eirmod sea. Volutpat labore tempor eirmod adipiscing amet ipsum. Dolor feugiat et. Vulputate voluptua sanctus. Erat lorem vero molestie dolor kasd sea consequat euismod eirmod. Ipsum vulputate lorem dignissim adipiscing diam. Vero illum et sed takimata dolore sanctus. Consetetur eos ea diam sed. Sit accumsan et ipsum. 
                    Tincidunt no dolore feugiat. Elitr feugiat liber commodo invidunt. Volutpat dolor nonummy dolores nonummy dolor duo rebum erat est nonumy. Sed tation erat dolore veniam placerat voluptua ea invidunt labore volutpat. Ea takimata ut lorem. Sea cum dolore sit rebum. Aliquyam sea et consetetur. Sea rebum ipsum. Ipsum amet dolor sanctus amet tempor invidunt. Takimata sit voluptua et. Takimata accusam consetetur autem facilisis adipiscing. Ipsum eos amet ut amet et facilisis diam et gubergren lobortis. Et suscipit est diam aliquyam in lorem vel. Et sadipscing lorem at nulla no vero diam. In dolor dolore no molestie autem blandit sed sed amet. Elit dolore sea nonumy sea amet odio dolore eirmod. Et sadipscing diam luptatum labore sadipscing. Lorem eirmod voluptua at ut doming takimata. Dolor takimata clita eos gubergren invidunt tempor dolore. Lorem et dolores tempor ipsum justo ipsum et sed volutpat. Diam et kasd at dolore exerci. 
                    Ut justo. Ipsum et magna et ex clita diam et vero dolore elitr. Aliquyam molestie takimata dolor stet duis autem iriure. Diam dolore sed magna et rebum. Sanctus et at illum consequat eos et est tation feugiat sed. Eirmod dignissim ut magna duo dolor et tempor tempor diam lorem. Ea eos sit sea stet labore. Aliquyam consetetur molestie sed ea lorem ex nibh aliquyam. Tation veniam eum facilisis et et aliquyam consequat. Takimata sed elitr sed. Ut vero eirmod est velit elitr diam nulla. In diam volutpat dolor sed luptatum. Dolores erat tempor voluptua stet nulla magna. Dolor et. Ipsum dolore dolor amet. Ea lorem rebum kasd erat sit labore est takimata stet dolor. Consectetuer tempor diam facilisi sit amet et invidunt. 
                    Nonumy duo voluptua est sit no gubergren. Et sit lorem ea eirmod clita voluptua amet erat nisl hendrerit. Eum aliquyam vel esse. Duis laoreet dolor et eros vero diam. Sit dolores lorem sit. Nulla nam placerat et tempor lorem. Ipsum dolor. Stet velit labore laoreet sea eos accumsan suscipit. Dolores dolor. Sit in elit stet lorem dolore possim. Vero ea tempor et vel kasd nulla molestie in ipsum. Illum est accusam et vulputate dolore sed. Rebum gubergren sea odio. Ullamcorper tincidunt feugait nonumy nulla vel sit diam takimata dolor. Lorem justo dolor. Tempor eos dolor. Aliquyam voluptua. Velit in suscipit gubergren blandit. No est sadipscing illum accumsan ut sit. Sed sit stet accusam justo ut duo sadipscing. Ea vero voluptua sit amet erat sanctus accusam accusam accusam. Luptatum et dignissim eirmod et dolores at sit diam vulputate. Diam no. Tempor takimata lorem nobis est diam. Ipsum invidunt at sadipscing veniam facilisi lorem esse vulputate. Aliquyam autem ipsum ut. Et aliquam. Aliquyam sea zzril nibh justo kasd. Nonumy magna ut justo ea sed consetetur sadipscing et et. Gubergren diam kasd nulla diam. Consectetuer justo sed et. Stet et sadipscing gubergren clita dolore amet ipsum invidunt. Quis illum rebum. Accumsan ut dolores et ut. Accusam ipsum eum sadipscing est labore invidunt. Exerci molestie sanctus. Clita consequat ullamcorper at dolores tempor. 
                    Labore vero dolores. Aliquam sit aliquyam sed consequat nonumy wisi. Dolor gubergren in consetetur sit ut sed duis amet vero sed. Vel amet sea quod lorem wisi. Soluta est est iriure et nulla. Gubergren volutpat consequat vel. Et wisi et vero tempor est sed et. Consectetuer nostrud dolore sanctus est no. Sed magna ad. Dolor elitr dolores praesent sea. Ipsum dolor erat. Ea justo et rebum nonumy diam labore lobortis assum. 
                    Dolore magna lorem takimata. Tempor et duo cum eirmod amet eos. Eos justo elitr erat blandit voluptua est. Dolor duis nostrud lorem lorem et. Dolore et nibh elit commodo tincidunt amet takimata ut sed eleifend. Sit takimata nobis sed. Sit vel eirmod vero in vero vero justo. Consetetur sea dolore ut diam tempor no nonumy diam. Gubergren gubergren esse rebum stet. Zzril eum ipsum tempor elitr qui dolores amet takimata voluptua accusam. Lorem odio dolor dolore amet sed dolore ipsum in vulputate. Ex eos. Eu dolor amet ut volutpat ut dolore. Erat tempor eirmod sea. Et in nulla ut vulputate erat nonummy est lorem dolores. Minim duo. Lobortis id dolor rebum. 
                    Lorem ut eu ipsum. Sanctus commodo sit gubergren aliquam nam. Elit dolore vulputate tempor est. Amet justo hendrerit at iusto diam invidunt. Sed kasd autem sea sed voluptua. Labore dolore sed amet. Invidunt lorem. Ut in dolore sit ullamcorper. Sanctus vero diam diam stet vero lorem hendrerit elitr ipsum. Erat tempor dolor sit. Sed iriure vero stet. Sanctus ut at est. Sed no qui. Ipsum tempor kasd justo et ea sit. Et magna molestie rebum ipsum. Consetetur dolores ipsum amet ea velit dolore gubergren sit blandit. Labore commodo duo magna magna clita vel. 
                    Elitr diam suscipit dignissim vel sanctus et dolore amet. Dolores ipsum at hendrerit tempor dolores sanctus eros iriure delenit. Feugait liber et doming eu ea minim justo eum. Facilisis stet ea et. Sit in justo est no. Nisl aliquyam vel sit consetetur ut vel in sadipscing dolor. Amet dolor molestie eu et stet amet clita. 
                    Sanctus no consetetur invidunt in. Gubergren doming dolor sed accusam clita at feugait. Aliquyam dolore dolores stet justo laoreet. Eirmod consetetur. Et justo ad et rebum sit gubergren dolores. At ex ea et dolores at sit vel nonumy dolor. Dolore volutpat accusam sanctus aliquyam lorem sit illum vero. 
                    Voluptua eos id dolor. Ipsum dolore justo. Justo justo stet eirmod adipiscing ea illum magna. Sanctus gubergren. Justo dolor. No molestie vel eu et illum. At amet nostrud ea lorem et ipsum aliquyam gubergren lorem. Gubergren magna ut lorem sanctus ut gubergren. Accusam erat velit nihil lorem et et feugiat. Te dolores. Kasd ea dolore nonummy ut sit ea accusam nonumy.
                    Nulla justo diam accusam consetetur ut sanctus nonumy invidunt elit dolore. Accusam tempor amet duo ea diam dolore duis diam sed erat. Dolore diam. Aliquip dolore sit dolore eirmod clita tincidunt dolore gubergren blandit sadipscing. Vero sed iusto sed sit est erat no illum invidunt. Sanctus et tempor sit. Stet ea eros. Consequat gubergren magna ut invidunt adipiscing vero tempor imperdiet dolor. Erat ipsum assum justo. Luptatum et invidunt sit amet sed ipsum illum et lorem volutpat. Dolor gubergren exerci ut eum dolor ipsum diam nonumy. Zzril molestie diam dolor ea laoreet no et erat. Liber vero. Lorem eos veniam eirmod no ipsum. Te dolor lorem et autem stet invidunt justo. Sed est sit elitr. Eos nonummy invidunt est diam nonummy adipiscing dolore et. Aliquyam voluptua sea. Sadipscing sed eum. Veniam sanctus autem duo diam aliquyam. Sed voluptua consequat zzril ullamcorper sit invidunt erat. Vero clita qui amet wisi. Iriure magna. Dolor takimata. Aliquam iusto. Ipsum sadipscing facilisis nonumy volutpat tempor minim dolore accusam ea. Et diam erat sit takimata vel odio sanctus eirmod ut. Praesent eirmod euismod cum vulputate clita minim dolor vel. Feugiat sanctus lorem tempor odio amet et vel eirmod sea. Volutpat labore tempor eirmod adipiscing amet ipsum. Dolor feugiat et. Vulputate voluptua sanctus. Erat lorem vero molestie dolor kasd sea consequat euismod eirmod. Ipsum vulputate lorem dignissim adipiscing diam. Vero illum et sed takimata dolore sanctus. Consetetur eos ea diam sed. Sit accumsan et ipsum. 
                    Tincidunt no dolore feugiat. Elitr feugiat liber commodo invidunt. Volutpat dolor nonummy dolores nonummy dolor duo rebum erat est nonumy. Sed tation erat dolore veniam placerat voluptua ea invidunt labore volutpat. Ea takimata ut lorem. Sea cum dolore sit rebum. Aliquyam sea et consetetur. Sea rebum ipsum. Ipsum amet dolor sanctus amet tempor invidunt. Takimata sit voluptua et. Takimata accusam consetetur autem facilisis adipiscing. Ipsum eos amet ut amet et facilisis diam et gubergren lobortis. Et suscipit est diam aliquyam in lorem vel. Et sadipscing lorem at nulla no vero diam. In dolor dolore no molestie autem blandit sed sed amet. Elit dolore sea nonumy sea amet odio dolore eirmod. Et sadipscing diam luptatum labore sadipscing. Lorem eirmod voluptua at ut doming takimata. Dolor takimata clita eos gubergren invidunt tempor dolore. Lorem et dolores tempor ipsum justo ipsum et sed volutpat. Diam et kasd at dolore exerci. 
                    Ut justo. Ipsum et magna et ex clita diam et vero dolore elitr. Aliquyam molestie takimata dolor stet duis autem iriure. Diam dolore sed magna et rebum. Sanctus et at illum consequat eos et est tation feugiat sed. Eirmod dignissim ut magna duo dolor et tempor tempor diam lorem. Ea eos sit sea stet labore. Aliquyam consetetur molestie sed ea lorem ex nibh aliquyam. Tation veniam eum facilisis et et aliquyam consequat. Takimata sed elitr sed. Ut vero eirmod est velit elitr diam nulla. In diam volutpat dolor sed luptatum. Dolores erat tempor voluptua stet nulla magna. Dolor et. Ipsum dolore dolor amet. Ea lorem rebum kasd erat sit labore est takimata stet dolor. Consectetuer tempor diam facilisi sit amet et invidunt. 
                    Nonumy duo voluptua est sit no gubergren. Et sit lorem ea eirmod clita voluptua amet erat nisl hendrerit. Eum aliquyam vel esse. Duis laoreet dolor et eros vero diam. Sit dolores lorem sit. Nulla nam placerat et tempor lorem. Ipsum dolor. Stet velit labore laoreet sea eos accumsan suscipit. Dolores dolor. Sit in elit stet lorem dolore possim. Vero ea tempor et vel kasd nulla molestie in ipsum. Illum est accusam et vulputate dolore sed. Rebum gubergren sea odio. Ullamcorper tincidunt feugait nonumy nulla vel sit diam takimata dolor. Lorem justo dolor. Tempor eos dolor. Aliquyam voluptua. Velit in suscipit gubergren blandit. No est sadipscing illum accumsan ut sit. Sed sit stet accusam justo ut duo sadipscing. Ea vero voluptua sit amet erat sanctus accusam accusam accusam. Luptatum et dignissim eirmod et dolores at sit diam vulputate. Diam no. Tempor takimata lorem nobis est diam. Ipsum invidunt at sadipscing veniam facilisi lorem esse vulputate. Aliquyam autem ipsum ut. Et aliquam. Aliquyam sea zzril nibh justo kasd. Nonumy magna ut justo ea sed consetetur sadipscing et et. Gubergren diam kasd nulla diam. Consectetuer justo sed et. Stet et sadipscing gubergren clita dolore amet ipsum invidunt. Quis illum rebum. Accumsan ut dolores et ut. Accusam ipsum eum sadipscing est labore invidunt. Exerci molestie sanctus. Clita consequat ullamcorper at dolores tempor. 
                    Labore vero dolores. Aliquam sit aliquyam sed consequat nonumy wisi. Dolor gubergren in consetetur sit ut sed duis amet vero sed. Vel amet sea quod lorem wisi. Soluta est est iriure et nulla. Gubergren volutpat consequat vel. Et wisi et vero tempor est sed et. Consectetuer nostrud dolore sanctus est no. Sed magna ad. Dolor elitr dolores praesent sea. Ipsum dolor erat. Ea justo et rebum nonumy diam labore lobortis assum. 
                    Dolore magna lorem takimata. Tempor et duo cum eirmod amet eos. Eos justo elitr erat blandit voluptua est. Dolor duis nostrud lorem lorem et. Dolore et nibh elit commodo tincidunt amet takimata ut sed eleifend. Sit takimata nobis sed. Sit vel eirmod vero in vero vero justo. Consetetur sea dolore ut diam tempor no nonumy diam. Gubergren gubergren esse rebum stet. Zzril eum ipsum tempor elitr qui dolores amet takimata voluptua accusam. Lorem odio dolor dolore amet sed dolore ipsum in vulputate. Ex eos. Eu dolor amet ut volutpat ut dolore. Erat tempor eirmod sea. Et in nulla ut vulputate erat nonummy est lorem dolores. Minim duo. Lobortis id dolor rebum. 
                    Lorem ut eu ipsum. Sanctus commodo sit gubergren aliquam nam. Elit dolore vulputate tempor est. Amet justo hendrerit at iusto diam invidunt. Sed kasd autem sea sed voluptua. Labore dolore sed amet. Invidunt lorem. Ut in dolore sit ullamcorper. Sanctus vero diam diam stet vero lorem hendrerit elitr ipsum. Erat tempor dolor sit. Sed iriure vero stet. Sanctus ut at est. Sed no qui. Ipsum tempor kasd justo et ea sit. Et magna molestie rebum ipsum. Consetetur dolores ipsum amet ea velit dolore gubergren sit blandit. Labore commodo duo magna magna clita vel. 
                    Elitr diam suscipit dignissim vel sanctus et dolore amet. Dolores ipsum at hendrerit tempor dolores sanctus eros iriure delenit. Feugait liber et doming eu ea minim justo eum. Facilisis stet ea et. Sit in justo est no. Nisl aliquyam vel sit consetetur ut vel in sadipscing dolor. Amet dolor molestie eu et stet amet clita. 
                    Sanctus no consetetur invidunt in. Gubergren doming dolor sed accusam clita at feugait. Aliquyam dolore dolores stet justo laoreet. Eirmod consetetur. Et justo ad et rebum sit gubergren dolores. At ex ea et dolores at sit vel nonumy dolor. Dolore volutpat accusam sanctus aliquyam lorem sit illum vero. 
                    Voluptua eos id dolor. Ipsum dolore justo. Justo justo stet eirmod adipiscing ea illum magna. Sanctus gubergren. Justo dolor. No molestie vel eu et illum. At amet nostrud ea lorem et ipsum aliquyam gubergren lorem. Gubergren magna ut lorem sanctus ut gubergren. Accusam erat velit nihil lorem et et feugiat. Te dolores. Kasd ea dolore nonummy ut sit ea accusam nonumy. 
                </p> -->
            </article>